module.exports = {
    apps: [
        // API (backend) process
        {
            name: 'love-bin',
            script: './index.js',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '1G',
            env: {
                NODE_ENV: 'production',
                PORT: 3001,
                TZ: 'Africa/Addis_Ababa',
                BOT_TOKEN: '8497021561:AAFFo5LgBDOrOOSAsZHtSGvyeSBYqSrf2hw',
                RUN_TELEGRAM_BOT: 'false',
                ADMIN_BOOT_CODE: 'SuperSecret2018',
                WEBAPP_URL: 'https://fikirbingo.com',
                API_BASE_URL: 'http://localhost:3001',
                JWT_SECRET: 'your_super_secret_jwt_key_here_change_this',
                MONGODB_URI: 'mongodb+srv://meseretlealem8_db_user:dnvd1DJOd2AJKgZ0@funnybingo.qygmvoo.mongodb.net/?appName=funnybingo',
                AGENT_PHONE_NUMBERS: '+251994237676',
                AGENT_SERVICES: 'CBEBirr,CBE',
                SMS_WEBHOOK_SECRET: 'i_secreted_lealem'
            },
            error_file: './logs/api-err.log',
            out_file: './logs/api-out.log',
            time: true,
            kill_timeout: 5000,
            wait_ready: true,
            listen_timeout: 10000,
            max_restarts: 10,
            min_uptime: '10s',
            restart_delay: 4000
        },
        // Telegram bot process
        {
            name: 'fun-bingo-bot',
            script: './telegram/bot.js',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '512M',
            env: {
                NODE_ENV: 'production',
                TZ: 'Africa/Addis_Ababa',
                BOT_TOKEN: '8497021561:AAFFo5LgBDOrOOSAsZHtSGvyeSBYqSrf2hw',
                RUN_TELEGRAM_BOT: 'true',
                ADMIN_BOOT_CODE: 'SuperSecret2018',
                WEBAPP_URL: 'https://fikirbingo.com',
                API_BASE_URL: 'http://localhost:3001',
                API_URL: 'http://localhost:3001',
                MONGODB_URI: 'mongodb+srv://meseretlealem8_db_user:dnvd1DJOd2AJKgZ0@funnybingo.qygmvoo.mongodb.net/?appName=funnybingo'
            },
            error_file: './logs/bot-err.log',
            out_file: './logs/bot-out.log',
            time: true,
            kill_timeout: 5000,
            wait_ready: true,
            listen_timeout: 10000,
            max_restarts: 10,
            min_uptime: '10s',
            restart_delay: 4000
        },
        // Player bots - 20 automated game players with Ethiopian nicknames
        // All 20 bots: Stake 10 (Yared, Beti, Kalkidan, Dawit, Meaza, Birhanu, Liya, Kidus, Frehiwot, Tewodros, Mulugeta, Sara, Tadesse, Hana, Abebe, Alemayehu, Habtamu, Mebrat, Elias, Getachew)
        {
            name: 'bingo-player-bot-yared',
            script: './bots/playerBot.js',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '256M',
            env: {
                NODE_ENV: 'production',
                TZ: 'Africa/Addis_Ababa',
                JWT_TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OTkzNTcxNDc5OTFkYTk2MTNlMTlkZTQiLCJpYXQiOjE3NzEyNjM3Njd9.NyLzyXyIsb2G6przstPw3gw1drOLiZaQ0ESAxolfTYo',
                STAKE: '10',
                API_BASE: 'http://localhost:3001',
                WS_BASE: 'ws://localhost:3001',
                MONGODB_URI: 'mongodb+srv://meseretlealem8_db_user:dnvd1DJOd2AJKgZ0@funnybingo.qygmvoo.mongodb.net/?appName=funnybingo'
            },
            error_file: './logs/player-bot-yared-err.log',
            out_file: './logs/player-bot-yared-out.log',
            time: true,
            kill_timeout: 5000,
            max_restarts: 10,
            min_uptime: '10s',
            restart_delay: 4000
        },
        {
            name: 'bingo-player-bot-beti',
            script: './bots/playerBot.js',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '256M',
            env: {
                NODE_ENV: 'production',
                TZ: 'Africa/Addis_Ababa',
                JWT_TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OTkzNTcxODc5OTFkYTk2MTNlMTlkZjciLCJpYXQiOjE3NzEyNjM3Njl9.xPBsfKWzCqvzokv5E-B55ty695HL52WZqvgCiPQyrro',
                STAKE: '10',
                API_BASE: 'http://localhost:3001',
                WS_BASE: 'ws://localhost:3001',
                MONGODB_URI: 'mongodb+srv://meseretlealem8_db_user:dnvd1DJOd2AJKgZ0@funnybingo.qygmvoo.mongodb.net/?appName=funnybingo'
            },
            error_file: './logs/player-bot-beti-err.log',
            out_file: './logs/player-bot-beti-out.log',
            time: true,
            kill_timeout: 5000,
            max_restarts: 10,
            min_uptime: '10s',
            restart_delay: 4000
        },
        {
            name: 'bingo-player-bot-kalkidan',
            script: './bots/playerBot.js',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '256M',
            env: {
                NODE_ENV: 'production',
                TZ: 'Africa/Addis_Ababa',
                JWT_TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OTkzNTcxOTc5OTFkYTk2MTNlMTlkZmYiLCJpYXQiOjE3NzEyNjM3NzB9.tnA-eyfGHHZ2Hio95UOU49n-QnEj8_AeZCVFPDzclAI',
                STAKE: '10',
                API_BASE: 'http://localhost:3001',
                WS_BASE: 'ws://localhost:3001',
                MONGODB_URI: 'mongodb+srv://meseretlealem8_db_user:dnvd1DJOd2AJKgZ0@funnybingo.qygmvoo.mongodb.net/?appName=funnybingo'
            },
            error_file: './logs/player-bot-kalkidan-err.log',
            out_file: './logs/player-bot-kalkidan-out.log',
            time: true,
            kill_timeout: 5000,
            max_restarts: 10,
            min_uptime: '10s',
            restart_delay: 4000
        },
        {
            name: 'bingo-player-bot-dawit',
            script: './bots/playerBot.js',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '256M',
            env: {
                NODE_ENV: 'production',
                TZ: 'Africa/Addis_Ababa',
                JWT_TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OTkzNTcxYTc5OTFkYTk2MTNlMTllMDciLCJpYXQiOjE3NzEyNjM3NzJ9.gtMhOUJ2n6m-VVz1g2T3G2hNMuhSbc5r5R2zYNMpOHQ',
                STAKE: '10',
                API_BASE: 'http://localhost:3001',
                WS_BASE: 'ws://localhost:3001',
                MONGODB_URI: 'mongodb+srv://meseretlealem8_db_user:dnvd1DJOd2AJKgZ0@funnybingo.qygmvoo.mongodb.net/?appName=funnybingo'
            },
            error_file: './logs/player-bot-dawit-err.log',
            out_file: './logs/player-bot-dawit-out.log',
            time: true,
            kill_timeout: 5000,
            max_restarts: 10,
            min_uptime: '10s',
            restart_delay: 4000
        },
        {
            name: 'bingo-player-bot-meaza',
            script: './bots/playerBot.js',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '256M',
            env: {
                NODE_ENV: 'production',
                TZ: 'Africa/Addis_Ababa',
                JWT_TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OTkzNTcxYzc5OTFkYTk2MTNlMTllMGYiLCJpYXQiOjE3NzEyNjM3NzN9.LeNgZE1fammpQvWzAgEN5PgQtovvLkxrfNSZ2OeqZfg',
                STAKE: '10',
                API_BASE: 'http://localhost:3001',
                WS_BASE: 'ws://localhost:3001',
                MONGODB_URI: 'mongodb+srv://meseretlealem8_db_user:dnvd1DJOd2AJKgZ0@funnybingo.qygmvoo.mongodb.net/?appName=funnybingo'
            },
            error_file: './logs/player-bot-meaza-err.log',
            out_file: './logs/player-bot-meaza-out.log',
            time: true,
            kill_timeout: 5000,
            max_restarts: 10,
            min_uptime: '10s',
            restart_delay: 4000
        },
        {
            name: 'bingo-player-bot-birhanu',
            script: './bots/playerBot.js',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '256M',
            env: {
                NODE_ENV: 'production',
                TZ: 'Africa/Addis_Ababa',
                JWT_TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OTkzNTcxZDc5OTFkYTk2MTNlMTllMTciLCJpYXQiOjE3NzEyNjM3NzR9.rBWf3SIdrt8UWVbkLNzyIfi1K6HQ33LeqIpxv43cNCE',
                STAKE: '10',
                API_BASE: 'http://localhost:3001',
                WS_BASE: 'ws://localhost:3001',
                MONGODB_URI: 'mongodb+srv://meseretlealem8_db_user:dnvd1DJOd2AJKgZ0@funnybingo.qygmvoo.mongodb.net/?appName=funnybingo'
            },
            error_file: './logs/player-bot-birhanu-err.log',
            out_file: './logs/player-bot-birhanu-out.log',
            time: true,
            kill_timeout: 5000,
            max_restarts: 10,
            min_uptime: '10s',
            restart_delay: 4000
        },
        {
            name: 'bingo-player-bot-liya',
            script: './bots/playerBot.js',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '256M',
            env: {
                NODE_ENV: 'production',
                TZ: 'Africa/Addis_Ababa',
                JWT_TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OTkzNTcxZTc5OTFkYTk2MTNlMTllMWYiLCJpYXQiOjE3NzEyNjM3NzZ9.XolJnL97_JvYkC3sViRVbl7Pzd534ilFQL37wZBIwPI',
                STAKE: '10',
                API_BASE: 'http://localhost:3001',
                WS_BASE: 'ws://localhost:3001',
                MONGODB_URI: 'mongodb+srv://meseretlealem8_db_user:dnvd1DJOd2AJKgZ0@funnybingo.qygmvoo.mongodb.net/?appName=funnybingo'
            },
            error_file: './logs/player-bot-liya-err.log',
            out_file: './logs/player-bot-liya-out.log',
            time: true,
            kill_timeout: 5000,
            max_restarts: 10,
            min_uptime: '10s',
            restart_delay: 4000
        },
        {
            name: 'bingo-player-bot-kidus',
            script: './bots/playerBot.js',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '256M',
            env: {
                NODE_ENV: 'production',
                TZ: 'Africa/Addis_Ababa',
                JWT_TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OTkzNTcyMDc5OTFkYTk2MTNlMTllMjciLCJpYXQiOjE3NzEyNjM3Nzd9.8O6DoqceikMJO6Qs8pZyic5PZN9fpWzDZk13JKDHTjc',
                STAKE: '10',
                API_BASE: 'http://localhost:3001',
                WS_BASE: 'ws://localhost:3001',
                MONGODB_URI: 'mongodb+srv://meseretlealem8_db_user:dnvd1DJOd2AJKgZ0@funnybingo.qygmvoo.mongodb.net/?appName=funnybingo'
            },
            error_file: './logs/player-bot-kidus-err.log',
            out_file: './logs/player-bot-kidus-out.log',
            time: true,
            kill_timeout: 5000,
            max_restarts: 10,
            min_uptime: '10s',
            restart_delay: 4000
        },
        {
            name: 'bingo-player-bot-frehiwot',
            script: './bots/playerBot.js',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '256M',
            env: {
                NODE_ENV: 'production',
                TZ: 'Africa/Addis_Ababa',
                JWT_TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OTkzNTcyMTc5OTFkYTk2MTNlMTllMmYiLCJpYXQiOjE3NzEyNjM3Nzl9._OesLzbPvqMUPyL8c-8aGWGsutG0a8OZLZ01qOn_ODU',
                STAKE: '10',
                API_BASE: 'http://localhost:3001',
                WS_BASE: 'ws://localhost:3001',
                MONGODB_URI: 'mongodb+srv://meseretlealem8_db_user:dnvd1DJOd2AJKgZ0@funnybingo.qygmvoo.mongodb.net/?appName=funnybingo'
            },
            error_file: './logs/player-bot-frehiwot-err.log',
            out_file: './logs/player-bot-frehiwot-out.log',
            time: true,
            kill_timeout: 5000,
            max_restarts: 10,
            min_uptime: '10s',
            restart_delay: 4000
        },
        {
            name: 'bingo-player-bot-tewodros',
            script: './bots/playerBot.js',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '256M',
            env: {
                NODE_ENV: 'production',
                TZ: 'Africa/Addis_Ababa',
                JWT_TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OTkzNTcyMzc5OTFkYTk2MTNlMTllMzciLCJpYXQiOjE3NzEyNjM3ODB9.cEQPhaqAfl8K6jNR9VQqtbF762uo3Bwsbmwidp2DiVo',
                STAKE: '10',
                API_BASE: 'http://localhost:3001',
                WS_BASE: 'ws://localhost:3001',
                MONGODB_URI: 'mongodb+srv://meseretlealem8_db_user:dnvd1DJOd2AJKgZ0@funnybingo.qygmvoo.mongodb.net/?appName=funnybingo'
            },
            error_file: './logs/player-bot-tewodros-err.log',
            out_file: './logs/player-bot-tewodros-out.log',
            time: true,
            kill_timeout: 5000,
            max_restarts: 10,
            min_uptime: '10s',
            restart_delay: 4000
        },
        {
            name: 'bingo-player-bot-mulugeta',
            script: './bots/playerBot.js',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '256M',
            env: {
                NODE_ENV: 'production',
                TZ: 'Africa/Addis_Ababa',
                JWT_TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OTkzNTcyNTc5OTFkYTk2MTNlMTllM2YiLCJpYXQiOjE3NzEyNjM3ODJ9.8F6eJmmUjKhqCP6mlj2aZti3-7cHk3KuWx-UXqx6Bw8',
                STAKE: '10',
                API_BASE: 'http://localhost:3001',
                WS_BASE: 'ws://localhost:3001',
                MONGODB_URI: 'mongodb+srv://meseretlealem8_db_user:dnvd1DJOd2AJKgZ0@funnybingo.qygmvoo.mongodb.net/?appName=funnybingo'
            },
            error_file: './logs/player-bot-mulugeta-err.log',
            out_file: './logs/player-bot-mulugeta-out.log',
            time: true,
            kill_timeout: 5000,
            max_restarts: 10,
            min_uptime: '10s',
            restart_delay: 4000
        },
        {
            name: 'bingo-player-bot-sara',
            script: './bots/playerBot.js',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '256M',
            env: {
                NODE_ENV: 'production',
                TZ: 'Africa/Addis_Ababa',
                JWT_TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OTkzNTcyNjc5OTFkYTk2MTNlMTllNDciLCJpYXQiOjE3NzEyNjM3ODN9.yUozX6IaUifrQC360EWH6s7mUOxdpxis3vjCon6xwWY',
                STAKE: '10',
                API_BASE: 'http://localhost:3001',
                WS_BASE: 'ws://localhost:3001',
                MONGODB_URI: 'mongodb+srv://meseretlealem8_db_user:dnvd1DJOd2AJKgZ0@funnybingo.qygmvoo.mongodb.net/?appName=funnybingo'
            },
            error_file: './logs/player-bot-sara-err.log',
            out_file: './logs/player-bot-sara-out.log',
            time: true,
            kill_timeout: 5000,
            max_restarts: 10,
            min_uptime: '10s',
            restart_delay: 4000
        },
        {
            name: 'bingo-player-bot-tadesse',
            script: './bots/playerBot.js',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '256M',
            env: {
                NODE_ENV: 'production',
                TZ: 'Africa/Addis_Ababa',
                JWT_TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OTkzNTcyODc5OTFkYTk2MTNlMTllNGYiLCJpYXQiOjE3NzEyNjM3ODV9.yvId5lumLJwR5u-wOFYNWN83VWa7JQIzCPO04XcV8LQ',
                STAKE: '10',
                API_BASE: 'http://localhost:3001',
                WS_BASE: 'ws://localhost:3001',
                MONGODB_URI: 'mongodb+srv://meseretlealem8_db_user:dnvd1DJOd2AJKgZ0@funnybingo.qygmvoo.mongodb.net/?appName=funnybingo'
            },
            error_file: './logs/player-bot-tadesse-err.log',
            out_file: './logs/player-bot-tadesse-out.log',
            time: true,
            kill_timeout: 5000,
            max_restarts: 10,
            min_uptime: '10s',
            restart_delay: 4000
        },
        {
            name: 'bingo-player-bot-hana',
            script: './bots/playerBot.js',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '256M',
            env: {
                NODE_ENV: 'production',
                TZ: 'Africa/Addis_Ababa',
                JWT_TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OTkzNTcyOTc5OTFkYTk2MTNlMTllNTciLCJpYXQiOjE3NzEyNjM3ODZ9.JGLiuXqa60GLJpSFiFoY6bmj5qzCXF-_EUiReyD3P_k',
                STAKE: '10',
                API_BASE: 'http://localhost:3001',
                WS_BASE: 'ws://localhost:3001',
                MONGODB_URI: 'mongodb+srv://meseretlealem8_db_user:dnvd1DJOd2AJKgZ0@funnybingo.qygmvoo.mongodb.net/?appName=funnybingo'
            },
            error_file: './logs/player-bot-hana-err.log',
            out_file: './logs/player-bot-hana-out.log',
            time: true,
            kill_timeout: 5000,
            max_restarts: 10,
            min_uptime: '10s',
            restart_delay: 4000
        },
        {
            name: 'bingo-player-bot-abebe',
            script: './bots/playerBot.js',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '256M',
            env: {
                NODE_ENV: 'production',
                TZ: 'Africa/Addis_Ababa',
                JWT_TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OTkzNTcyYTc5OTFkYTk2MTNlMTllNWYiLCJpYXQiOjE3NzEyNjM3ODh9.RfhOqLxvBL18rpH6mE4YDD4V793-lv1tSkCyl_TupT4',
                STAKE: '10',
                API_BASE: 'http://localhost:3001',
                WS_BASE: 'ws://localhost:3001',
                MONGODB_URI: 'mongodb+srv://meseretlealem8_db_user:dnvd1DJOd2AJKgZ0@funnybingo.qygmvoo.mongodb.net/?appName=funnybingo'
            },
            error_file: './logs/player-bot-abebe-err.log',
            out_file: './logs/player-bot-abebe-out.log',
            time: true,
            kill_timeout: 5000,
            max_restarts: 10,
            min_uptime: '10s',
            restart_delay: 4000
        },
        // Bots 16-20: Stake 10
        {
            name: 'bingo-player-bot-alemayehu',
            script: './bots/playerBot.js',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '256M',
            env: {
                NODE_ENV: 'production',
                TZ: 'Africa/Addis_Ababa',
                JWT_TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OTkzNTcyYzc5OTFkYTk2MTNlMTllNjciLCJpYXQiOjE3NzEyNjM3ODl9.NekkWZQdG5DbnCgeXslyKod94tbM7KBehB5Q3AqpHNA',
                STAKE: '10',
                API_BASE: 'http://localhost:3001',
                WS_BASE: 'ws://localhost:3001',
                MONGODB_URI: 'mongodb+srv://meseretlealem8_db_user:dnvd1DJOd2AJKgZ0@funnybingo.qygmvoo.mongodb.net/?appName=funnybingo'
            },
            error_file: './logs/player-bot-alemayehu-err.log',
            out_file: './logs/player-bot-alemayehu-out.log',
            time: true,
            kill_timeout: 5000,
            max_restarts: 10,
            min_uptime: '10s',
            restart_delay: 4000
        },
        {
            name: 'bingo-player-bot-habtamu',
            script: './bots/playerBot.js',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '256M',
            env: {
                NODE_ENV: 'production',
                TZ: 'Africa/Addis_Ababa',
                JWT_TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OTkzNTcyZDc5OTFkYTk2MTNlMTllNmYiLCJpYXQiOjE3NzEyNjM3OTB9.Z8f0D2tMd_KHnamLCm-eB6XB3UUKahidk7nIJlnBy2U',
                STAKE: '10',
                API_BASE: 'http://localhost:3001',
                WS_BASE: 'ws://localhost:3001',
                MONGODB_URI: 'mongodb+srv://meseretlealem8_db_user:dnvd1DJOd2AJKgZ0@funnybingo.qygmvoo.mongodb.net/?appName=funnybingo'
            },
            error_file: './logs/player-bot-habtamu-err.log',
            out_file: './logs/player-bot-habtamu-out.log',
            time: true,
            kill_timeout: 5000,
            max_restarts: 10,
            min_uptime: '10s',
            restart_delay: 4000
        },
        {
            name: 'bingo-player-bot-mebrat',
            script: './bots/playerBot.js',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '256M',
            env: {
                NODE_ENV: 'production',
                TZ: 'Africa/Addis_Ababa',
                JWT_TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OTkzNTcyZjc5OTFkYTk2MTNlMTllNzciLCJpYXQiOjE3NzEyNjM3OTJ9.YsoWcptc8Z4xkkwNOfkWyMbPFI6r9CAJ5xqeHQ9aJTI',
                STAKE: '10',
                API_BASE: 'http://localhost:3001',
                WS_BASE: 'ws://localhost:3001',
                MONGODB_URI: 'mongodb+srv://meseretlealem8_db_user:dnvd1DJOd2AJKgZ0@funnybingo.qygmvoo.mongodb.net/?appName=funnybingo'
            },
            error_file: './logs/player-bot-mebrat-err.log',
            out_file: './logs/player-bot-mebrat-out.log',
            time: true,
            kill_timeout: 5000,
            max_restarts: 10,
            min_uptime: '10s',
            restart_delay: 4000
        },
        {
            name: 'bingo-player-bot-elias',
            script: './bots/playerBot.js',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '256M',
            env: {
                NODE_ENV: 'production',
                TZ: 'Africa/Addis_Ababa',
                JWT_TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OTkzNTczMDc5OTFkYTk2MTNlMTllN2YiLCJpYXQiOjE3NzEyNjM3OTN9.db_ETAxGyGXa1dRury-Rk9OJxJ7nHUe4UQTUpzlwfpM',
                STAKE: '10',
                API_BASE: 'http://localhost:3001',
                WS_BASE: 'ws://localhost:3001',
                MONGODB_URI: 'mongodb+srv://meseretlealem8_db_user:dnvd1DJOd2AJKgZ0@funnybingo.qygmvoo.mongodb.net/?appName=funnybingo'
            },
            error_file: './logs/player-bot-elias-err.log',
            out_file: './logs/player-bot-elias-out.log',
            time: true,
            kill_timeout: 5000,
            max_restarts: 10,
            min_uptime: '10s',
            restart_delay: 4000
        },
        {
            name: 'bingo-player-bot-getachew',
            script: './bots/playerBot.js',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '256M',
            env: {
                NODE_ENV: 'production',
                TZ: 'Africa/Addis_Ababa',
                JWT_TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OTkzNTczMTc5OTFkYTk2MTNlMTllODciLCJpYXQiOjE3NzEyNjM3OTR9.Z_3eSj5eq_YU6FS_jbNofTjDkAVNj-jlXM3cQQU_aVE',
                STAKE: '10',
                API_BASE: 'http://localhost:3001',
                WS_BASE: 'ws://localhost:3001',
                MONGODB_URI: 'mongodb+srv://meseretlealem8_db_user:dnvd1DJOd2AJKgZ0@funnybingo.qygmvoo.mongodb.net/?appName=funnybingo'
            },
            error_file: './logs/player-bot-getachew-err.log',
            out_file: './logs/player-bot-getachew-out.log',
            time: true,
            kill_timeout: 5000,
            max_restarts: 10,
            min_uptime: '10s',
            restart_delay: 4000
        }
    ]
};
