module.exports = {
    apps: [
        // API (backend) process
        {
            name: 'love-bin',
            script: './index.js',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '1G',
            env: {
                NODE_ENV: 'production',
                PORT: 3001,
                TZ: 'Africa/Addis_Ababa',
                BOT_TOKEN: '8497021561:AAFFo5LgBDOrOOSAsZHtSGvyeSBYqSrf2hw',
                RUN_TELEGRAM_BOT: 'false',
                ADMIN_BOOT_CODE: 'SuperSecret2018',
                WEBAPP_URL: 'https://fikirbingo.com',
                API_BASE_URL: 'http://localhost:3001',
                JWT_SECRET: 'your_super_secret_jwt_key_here_change_this',
                MONGODB_URI: 'mongodb+srv://meseretlealem8_db_user:dnvd1DJOd2AJKgZ0@funnybingo.qygmvoo.mongodb.net/?appName=funnybingo',
                AGENT_PHONE_NUMBERS: '+251994237676',
                AGENT_SERVICES: 'CBEBirr,CBE',
                SMS_WEBHOOK_SECRET: 'i_secreted_lealem'
            },
            error_file: './logs/api-err.log',
            out_file: './logs/api-out.log',
            time: true,
            kill_timeout: 5000,
            wait_ready: true,
            listen_timeout: 10000,
            max_restarts: 10,
            min_uptime: '10s',
            restart_delay: 4000
        },
        // Telegram bot process
        {
            name: 'fun-bingo-bot',
            script: './telegram/bot.js',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '512M',
            env: {
                NODE_ENV: 'production',
                TZ: 'Africa/Addis_Ababa',
                BOT_TOKEN: '8497021561:AAFFo5LgBDOrOOSAsZHtSGvyeSBYqSrf2hw',
                RUN_TELEGRAM_BOT: 'true',
                WEBAPP_URL: 'https://fikirbingo.com',
                API_BASE_URL: 'http://localhost:3001',
                API_URL: 'http://localhost:3001',
                MONGODB_URI: 'mongodb+srv://meseretlealem8_db_user:dnvd1DJOd2AJKgZ0@funnybingo.qygmvoo.mongodb.net/?appName=funnybingo'
            },
            error_file: './logs/bot-err.log',
            out_file: './logs/bot-out.log',
            time: true,
            kill_timeout: 5000,
            wait_ready: true,
            listen_timeout: 10000,
            max_restarts: 10,
            min_uptime: '10s',
            restart_delay: 4000
        },
        // Player bots - 20 automated game players with Ethiopian nicknames
        // Bots 1-15: Stake 10 (Yared, Beti, Kalkidan, Dawit, Meaza, Birhanu, Liya, Kidus, Frehiwot, Tewodros, Mulugeta, Sara, Tadesse, Hana, Abebe)
        // Bots 16-20: Stake 25 (Alemayehu, Habtamu, Mebrat, Elias, Getachew)
        {
            name: 'bingo-player-bot-yared',
            script: './bots/playerBot.js',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '256M',
            env: {
                NODE_ENV: 'production',
                TZ: 'Africa/Addis_Ababa',
                JWT_TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OTE5OTQwZGUyZGM1MWI0NWQ2Njg1MjMiLCJpYXQiOjE3NjMyODQ1NDAsImV4cCI6MTc2Mzg4OTM0MH0.X7VeMtfCw1Bf3S4SVWXRacWWQnHZtxhpBj3v9rvC60k',
                STAKE: '10',
                API_BASE: 'http://localhost:3001',
                WS_BASE: 'ws://localhost:3001',
                MONGODB_URI: 'mongodb+srv://meseretlealem8_db_user:dnvd1DJOd2AJKgZ0@funnybingo.qygmvoo.mongodb.net/?appName=funnybingo'
            },
            error_file: './logs/player-bot-yared-err.log',
            out_file: './logs/player-bot-yared-out.log',
            time: true,
            kill_timeout: 5000,
            max_restarts: 10,
            min_uptime: '10s',
            restart_delay: 4000
        },
        {
            name: 'bingo-player-bot-beti',
            script: './bots/playerBot.js',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '256M',
            env: {
                NODE_ENV: 'production',
                TZ: 'Africa/Addis_Ababa',
                JWT_TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OTE5OTQwZWUyZGM1MWI0NWQ2Njg1MzYiLCJpYXQiOjE3NjMyODQ1NDAsImV4cCI6MTc2Mzg4OTM0MH0.FKMqv6RDKYOFuFfT-MZfQ8BuH-q19n_NB3VzVV5PwYg',
                STAKE: '10',
                API_BASE: 'http://localhost:3001',
                WS_BASE: 'ws://localhost:3001',
                MONGODB_URI: 'mongodb+srv://meseretlealem8_db_user:dnvd1DJOd2AJKgZ0@funnybingo.qygmvoo.mongodb.net/?appName=funnybingo'
            },
            error_file: './logs/player-bot-beti-err.log',
            out_file: './logs/player-bot-beti-out.log',
            time: true,
            kill_timeout: 5000,
            max_restarts: 10,
            min_uptime: '10s',
            restart_delay: 4000
        },
        {
            name: 'bingo-player-bot-kalkidan',
            script: './bots/playerBot.js',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '256M',
            env: {
                NODE_ENV: 'production',
                TZ: 'Africa/Addis_Ababa',
                JWT_TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OTE5OTQwZmUyZGM1MWI0NWQ2Njg1M2UiLCJpYXQiOjE3NjMyODQ1NDAsImV4cCI6MTc2Mzg4OTM0MH0.6BoktzmdrakDNjmTm0ggl1HRbcPLbGR_LdX9nxQgKKQ',
                STAKE: '10',
                API_BASE: 'http://localhost:3001',
                WS_BASE: 'ws://localhost:3001',
                MONGODB_URI: 'mongodb+srv://meseretlealem8_db_user:dnvd1DJOd2AJKgZ0@funnybingo.qygmvoo.mongodb.net/?appName=funnybingo'
            },
            error_file: './logs/player-bot-kalkidan-err.log',
            out_file: './logs/player-bot-kalkidan-out.log',
            time: true,
            kill_timeout: 5000,
            max_restarts: 10,
            min_uptime: '10s',
            restart_delay: 4000
        },
        {
            name: 'bingo-player-bot-dawit',
            script: './bots/playerBot.js',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '256M',
            env: {
                NODE_ENV: 'production',
                TZ: 'Africa/Addis_Ababa',
                JWT_TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OTE5OTQxMGUyZGM1MWI0NWQ2Njg1NDYiLCJpYXQiOjE3NjMyODQ1NDEsImV4cCI6MTc2Mzg4OTM0MX0.eh9oFGw2ZerTMcpvTcsv--Dfz8bDU15OydW9f_5vFQo',
                STAKE: '10',
                API_BASE: 'http://localhost:3001',
                WS_BASE: 'ws://localhost:3001',
                MONGODB_URI: 'mongodb+srv://meseretlealem8_db_user:dnvd1DJOd2AJKgZ0@funnybingo.qygmvoo.mongodb.net/?appName=funnybingo'
            },
            error_file: './logs/player-bot-dawit-err.log',
            out_file: './logs/player-bot-dawit-out.log',
            time: true,
            kill_timeout: 5000,
            max_restarts: 10,
            min_uptime: '10s',
            restart_delay: 4000
        },
        {
            name: 'bingo-player-bot-meaza',
            script: './bots/playerBot.js',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '256M',
            env: {
                NODE_ENV: 'production',
                TZ: 'Africa/Addis_Ababa',
                JWT_TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OTE5OTQxMGUyZGM1MWI0NWQ2Njg1NGUiLCJpYXQiOjE3NjMyODQ1NDEsImV4cCI6MTc2Mzg4OTM0MX0.NlMEsrCZVBfCt_06vziyswhbBZTmFZhnDCCHqbu8bAA',
                STAKE: '10',
                API_BASE: 'http://localhost:3001',
                WS_BASE: 'ws://localhost:3001',
                MONGODB_URI: 'mongodb+srv://meseretlealem8_db_user:dnvd1DJOd2AJKgZ0@funnybingo.qygmvoo.mongodb.net/?appName=funnybingo'
            },
            error_file: './logs/player-bot-meaza-err.log',
            out_file: './logs/player-bot-meaza-out.log',
            time: true,
            kill_timeout: 5000,
            max_restarts: 10,
            min_uptime: '10s',
            restart_delay: 4000
        },
        {
            name: 'bingo-player-bot-birhanu',
            script: './bots/playerBot.js',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '256M',
            env: {
                NODE_ENV: 'production',
                TZ: 'Africa/Addis_Ababa',
                JWT_TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OTE5OTQxMWUyZGM1MWI0NWQ2Njg1NTYiLCJpYXQiOjE3NjMyODQ1NDEsImV4cCI6MTc2Mzg4OTM0MX0.OEPN1bYaQqv0P2XuPZE-8jUHLoSbGrm_4movjHtJRqc',
                STAKE: '10',
                API_BASE: 'http://localhost:3001',
                WS_BASE: 'ws://localhost:3001',
                MONGODB_URI: 'mongodb+srv://meseretlealem8_db_user:dnvd1DJOd2AJKgZ0@funnybingo.qygmvoo.mongodb.net/?appName=funnybingo'
            },
            error_file: './logs/player-bot-birhanu-err.log',
            out_file: './logs/player-bot-birhanu-out.log',
            time: true,
            kill_timeout: 5000,
            max_restarts: 10,
            min_uptime: '10s',
            restart_delay: 4000
        },
        {
            name: 'bingo-player-bot-liya',
            script: './bots/playerBot.js',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '256M',
            env: {
                NODE_ENV: 'production',
                TZ: 'Africa/Addis_Ababa',
                JWT_TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OTE5OTQxMmUyZGM1MWI0NWQ2Njg1NWUiLCJpYXQiOjE3NjMyODQ1NDEsImV4cCI6MTc2Mzg4OTM0MX0.NoLiPrVOH7Gyy6EPoaXMTdbKVcJD2avWyTjsl7JAHeI',
                STAKE: '10',
                API_BASE: 'http://localhost:3001',
                WS_BASE: 'ws://localhost:3001',
                MONGODB_URI: 'mongodb+srv://meseretlealem8_db_user:dnvd1DJOd2AJKgZ0@funnybingo.qygmvoo.mongodb.net/?appName=funnybingo'
            },
            error_file: './logs/player-bot-liya-err.log',
            out_file: './logs/player-bot-liya-out.log',
            time: true,
            kill_timeout: 5000,
            max_restarts: 10,
            min_uptime: '10s',
            restart_delay: 4000
        },
        {
            name: 'bingo-player-bot-kidus',
            script: './bots/playerBot.js',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '256M',
            env: {
                NODE_ENV: 'production',
                TZ: 'Africa/Addis_Ababa',
                JWT_TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OTE5OTQxMmUyZGM1MWI0NWQ2Njg1NjYiLCJpYXQiOjE3NjMyODQ1NDEsImV4cCI6MTc2Mzg4OTM0MX0.WR-yO84y3k-ruNX5nIB656XJ9KoEZnXurvuoFcRav9I',
                STAKE: '10',
                API_BASE: 'http://localhost:3001',
                WS_BASE: 'ws://localhost:3001',
                MONGODB_URI: 'mongodb+srv://meseretlealem8_db_user:dnvd1DJOd2AJKgZ0@funnybingo.qygmvoo.mongodb.net/?appName=funnybingo'
            },
            error_file: './logs/player-bot-kidus-err.log',
            out_file: './logs/player-bot-kidus-out.log',
            time: true,
            kill_timeout: 5000,
            max_restarts: 10,
            min_uptime: '10s',
            restart_delay: 4000
        },
        {
            name: 'bingo-player-bot-frehiwot',
            script: './bots/playerBot.js',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '256M',
            env: {
                NODE_ENV: 'production',
                TZ: 'Africa/Addis_Ababa',
                JWT_TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OTE5OTQxM2UyZGM1MWI0NWQ2Njg1NmUiLCJpYXQiOjE3NjMyODQ1NDIsImV4cCI6MTc2Mzg4OTM0Mn0._k44ryH0F140JrFb0ZuurRLbfc2AVvGP7gSvisDNxXA',
                STAKE: '10',
                API_BASE: 'http://localhost:3001',
                WS_BASE: 'ws://localhost:3001',
                MONGODB_URI: 'mongodb+srv://meseretlealem8_db_user:dnvd1DJOd2AJKgZ0@funnybingo.qygmvoo.mongodb.net/?appName=funnybingo'
            },
            error_file: './logs/player-bot-frehiwot-err.log',
            out_file: './logs/player-bot-frehiwot-out.log',
            time: true,
            kill_timeout: 5000,
            max_restarts: 10,
            min_uptime: '10s',
            restart_delay: 4000
        },
        {
            name: 'bingo-player-bot-tewodros',
            script: './bots/playerBot.js',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '256M',
            env: {
                NODE_ENV: 'production',
                TZ: 'Africa/Addis_Ababa',
                JWT_TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OTE5OTQxNGUyZGM1MWI0NWQ2Njg1NzYiLCJpYXQiOjE3NjMyODQ1NDIsImV4cCI6MTc2Mzg4OTM0Mn0.Ef8pt_e-oNTzBDPC1QQyZi1oUcORiGuTwjoeDwTJCmg',
                STAKE: '10',
                API_BASE: 'http://localhost:3001',
                WS_BASE: 'ws://localhost:3001',
                MONGODB_URI: 'mongodb+srv://meseretlealem8_db_user:dnvd1DJOd2AJKgZ0@funnybingo.qygmvoo.mongodb.net/?appName=funnybingo'
            },
            error_file: './logs/player-bot-tewodros-err.log',
            out_file: './logs/player-bot-tewodros-out.log',
            time: true,
            kill_timeout: 5000,
            max_restarts: 10,
            min_uptime: '10s',
            restart_delay: 4000
        },
        {
            name: 'bingo-player-bot-mulugeta',
            script: './bots/playerBot.js',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '256M',
            env: {
                NODE_ENV: 'production',
                TZ: 'Africa/Addis_Ababa',
                JWT_TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OTE5OTQxNWUyZGM1MWI0NWQ2Njg1N2UiLCJpYXQiOjE3NjMyODQ1NDIsImV4cCI6MTc2Mzg4OTM0Mn0.wiUEJMukJskTtsPLVWKsk5agQVUVGjoYEU1UQJLqr64',
                STAKE: '10',
                API_BASE: 'http://localhost:3001',
                WS_BASE: 'ws://localhost:3001',
                MONGODB_URI: 'mongodb+srv://meseretlealem8_db_user:dnvd1DJOd2AJKgZ0@funnybingo.qygmvoo.mongodb.net/?appName=funnybingo'
            },
            error_file: './logs/player-bot-mulugeta-err.log',
            out_file: './logs/player-bot-mulugeta-out.log',
            time: true,
            kill_timeout: 5000,
            max_restarts: 10,
            min_uptime: '10s',
            restart_delay: 4000
        },
        {
            name: 'bingo-player-bot-sara',
            script: './bots/playerBot.js',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '256M',
            env: {
                NODE_ENV: 'production',
                TZ: 'Africa/Addis_Ababa',
                JWT_TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OTE5OTQxNmUyZGM1MWI0NWQ2Njg1ODYiLCJpYXQiOjE3NjMyODQ1NDIsImV4cCI6MTc2Mzg4OTM0Mn0.d7eJGzZupb8SHLOM7ZK1jdeRByH53jookN9ve-HVChU',
                STAKE: '10',
                API_BASE: 'http://localhost:3001',
                WS_BASE: 'ws://localhost:3001',
                MONGODB_URI: 'mongodb+srv://meseretlealem8_db_user:dnvd1DJOd2AJKgZ0@funnybingo.qygmvoo.mongodb.net/?appName=funnybingo'
            },
            error_file: './logs/player-bot-sara-err.log',
            out_file: './logs/player-bot-sara-out.log',
            time: true,
            kill_timeout: 5000,
            max_restarts: 10,
            min_uptime: '10s',
            restart_delay: 4000
        },
        {
            name: 'bingo-player-bot-tadesse',
            script: './bots/playerBot.js',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '256M',
            env: {
                NODE_ENV: 'production',
                TZ: 'Africa/Addis_Ababa',
                JWT_TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OTE5OTQxNmUyZGM1MWI0NWQ2Njg1OGUiLCJpYXQiOjE3NjMyODQ1NDMsImV4cCI6MTc2Mzg4OTM0M30.-LOb-fZpZ0i1okAc74e-7fTFAVLvkdaNsoXZXC-cm_4',
                STAKE: '10',
                API_BASE: 'http://localhost:3001',
                WS_BASE: 'ws://localhost:3001',
                MONGODB_URI: 'mongodb+srv://meseretlealem8_db_user:dnvd1DJOd2AJKgZ0@funnybingo.qygmvoo.mongodb.net/?appName=funnybingo'
            },
            error_file: './logs/player-bot-tadesse-err.log',
            out_file: './logs/player-bot-tadesse-out.log',
            time: true,
            kill_timeout: 5000,
            max_restarts: 10,
            min_uptime: '10s',
            restart_delay: 4000
        },
        {
            name: 'bingo-player-bot-hana',
            script: './bots/playerBot.js',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '256M',
            env: {
                NODE_ENV: 'production',
                TZ: 'Africa/Addis_Ababa',
                JWT_TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OTE5OTQxN2UyZGM1MWI0NWQ2Njg1OTYiLCJpYXQiOjE3NjMyODQ1NDMsImV4cCI6MTc2Mzg4OTM0M30.UzRCROOaodtSWcjIzO310RQ_14ZCIrwWtWgzKomDQv0',
                STAKE: '10',
                API_BASE: 'http://localhost:3001',
                WS_BASE: 'ws://localhost:3001',
                MONGODB_URI: 'mongodb+srv://meseretlealem8_db_user:dnvd1DJOd2AJKgZ0@funnybingo.qygmvoo.mongodb.net/?appName=funnybingo'
            },
            error_file: './logs/player-bot-hana-err.log',
            out_file: './logs/player-bot-hana-out.log',
            time: true,
            kill_timeout: 5000,
            max_restarts: 10,
            min_uptime: '10s',
            restart_delay: 4000
        },
        {
            name: 'bingo-player-bot-abebe',
            script: './bots/playerBot.js',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '256M',
            env: {
                NODE_ENV: 'production',
                TZ: 'Africa/Addis_Ababa',
                JWT_TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OTE5OTQxOGUyZGM1MWI0NWQ2Njg1OWUiLCJpYXQiOjE3NjMyODQ1NDMsImV4cCI6MTc2Mzg4OTM0M30.LUkyBu59Z5CRULifLfqTrB3AlTWhzEgOXN7NsrPFpVk',
                STAKE: '10',
                API_BASE: 'http://localhost:3001',
                WS_BASE: 'ws://localhost:3001',
                MONGODB_URI: 'mongodb+srv://meseretlealem8_db_user:dnvd1DJOd2AJKgZ0@funnybingo.qygmvoo.mongodb.net/?appName=funnybingo'
            },
            error_file: './logs/player-bot-abebe-err.log',
            out_file: './logs/player-bot-abebe-out.log',
            time: true,
            kill_timeout: 5000,
            max_restarts: 10,
            min_uptime: '10s',
            restart_delay: 4000
        },
        // Bots 16-20: Stake 25
        {
            name: 'bingo-player-bot-alemayehu',
            script: './bots/playerBot.js',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '256M',
            env: {
                NODE_ENV: 'production',
                TZ: 'Africa/Addis_Ababa',
                JWT_TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OTE5OTYzZjQ1ZDY1NDllNGFiYjQ0ODEiLCJpYXQiOjE3NjMyODQ1NDQsImV4cCI6MTc2Mzg4OTM0NH0._VXHtM_yqZgqtNMxD6CCgmzlTGf7NU1n8eOqGVe5xQ4',
                STAKE: '25',
                API_BASE: 'http://localhost:3001',
                WS_BASE: 'ws://localhost:3001',
                MONGODB_URI: 'mongodb+srv://meseretlealem8_db_user:dnvd1DJOd2AJKgZ0@funnybingo.qygmvoo.mongodb.net/?appName=funnybingo'
            },
            error_file: './logs/player-bot-alemayehu-err.log',
            out_file: './logs/player-bot-alemayehu-out.log',
            time: true,
            kill_timeout: 5000,
            max_restarts: 10,
            min_uptime: '10s',
            restart_delay: 4000
        },
        {
            name: 'bingo-player-bot-habtamu',
            script: './bots/playerBot.js',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '256M',
            env: {
                NODE_ENV: 'production',
                TZ: 'Africa/Addis_Ababa',
                JWT_TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OTE5OTY0MDQ1ZDY1NDllNGFiYjQ0ODkiLCJpYXQiOjE3NjMyODQ1NDQsImV4cCI6MTc2Mzg4OTM0NH0.KH02VBrFamRcHloZsNOTnk8pAbriUu4h58lwR_ojNVY',
                STAKE: '25',
                API_BASE: 'http://localhost:3001',
                WS_BASE: 'ws://localhost:3001',
                MONGODB_URI: 'mongodb+srv://meseretlealem8_db_user:dnvd1DJOd2AJKgZ0@funnybingo.qygmvoo.mongodb.net/?appName=funnybingo'
            },
            error_file: './logs/player-bot-habtamu-err.log',
            out_file: './logs/player-bot-habtamu-out.log',
            time: true,
            kill_timeout: 5000,
            max_restarts: 10,
            min_uptime: '10s',
            restart_delay: 4000
        },
        {
            name: 'bingo-player-bot-mebrat',
            script: './bots/playerBot.js',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '256M',
            env: {
                NODE_ENV: 'production',
                TZ: 'Africa/Addis_Ababa',
                JWT_TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OTE5OTY0MTQ1ZDY1NDllNGFiYjQ0OTEiLCJpYXQiOjE3NjMyODQ1NDUsImV4cCI6MTc2Mzg4OTM0NX0.C6IrPrtfMn3e-3IRDYLyNmtd0oAr6GbcbPuEjPwa-SE',
                STAKE: '25',
                API_BASE: 'http://localhost:3001',
                WS_BASE: 'ws://localhost:3001',
                MONGODB_URI: 'mongodb+srv://meseretlealem8_db_user:dnvd1DJOd2AJKgZ0@funnybingo.qygmvoo.mongodb.net/?appName=funnybingo'
            },
            error_file: './logs/player-bot-mebrat-err.log',
            out_file: './logs/player-bot-mebrat-out.log',
            time: true,
            kill_timeout: 5000,
            max_restarts: 10,
            min_uptime: '10s',
            restart_delay: 4000
        },
        {
            name: 'bingo-player-bot-elias',
            script: './bots/playerBot.js',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '256M',
            env: {
                NODE_ENV: 'production',
                TZ: 'Africa/Addis_Ababa',
                JWT_TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OTE5OTY0MTQ1ZDY1NDllNGFiYjQ0OTkiLCJpYXQiOjE3NjMyODQ1NDYsImV4cCI6MTc2Mzg4OTM0Nn0.0JLqXF0v4NVlpHmkoKjbfcR_ZK32c-JvVBn-eMTaZss',
                STAKE: '25',
                API_BASE: 'http://localhost:3001',
                WS_BASE: 'ws://localhost:3001',
                MONGODB_URI: 'mongodb+srv://meseretlealem8_db_user:dnvd1DJOd2AJKgZ0@funnybingo.qygmvoo.mongodb.net/?appName=funnybingo'
            },
            error_file: './logs/player-bot-elias-err.log',
            out_file: './logs/player-bot-elias-out.log',
            time: true,
            kill_timeout: 5000,
            max_restarts: 10,
            min_uptime: '10s',
            restart_delay: 4000
        },
        {
            name: 'bingo-player-bot-getachew',
            script: './bots/playerBot.js',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '256M',
            env: {
                NODE_ENV: 'production',
                TZ: 'Africa/Addis_Ababa',
                JWT_TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OTE5OTY0MjQ1ZDY1NDllNGFiYjQ0YTEiLCJpYXQiOjE3NjMyODQ1NDYsImV4cCI6MTc2Mzg4OTM0Nn0.NMMFc7C0SAzwsDOXFZEQfaobIf6nFFZzeK9MKORNgtY',
                STAKE: '25',
                API_BASE: 'http://localhost:3001',
                WS_BASE: 'ws://localhost:3001',
                MONGODB_URI: 'mongodb+srv://meseretlealem8_db_user:dnvd1DJOd2AJKgZ0@funnybingo.qygmvoo.mongodb.net/?appName=funnybingo'
            },
            error_file: './logs/player-bot-getachew-err.log',
            out_file: './logs/player-bot-getachew-out.log',
            time: true,
            kill_timeout: 5000,
            max_restarts: 10,
            min_uptime: '10s',
            restart_delay: 4000
        }
    ]
};
